/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'svanurjoh' at '10/24/16 8:52 PM' with Gradle 3.1
 *
 * @author svanurjoh, @date 10/24/16 8:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
